##Jamison Wilkes
##DNS Lab

import subprocess
import time

print("#1")
print("#Begin DNS search processes")
print("__________________________")
print()
print("Run nslookup for weber.edu")
subprocess.call(["nslookup","weber.edu"])
print()
print("Run ns dig for weber.edu")
subprocess.call(["dig","weber.edu"])
print()
print("Run Host for weber.edu")
subprocess.call(["host","weber.edu"])

time.sleep(3)

print("#2")
print("#Begin DNS search processes")
print("__________________________")
print()
print("Run nslookup for deseretnews.com")
subprocess.call(["nslookup","deseretnews.com"])
print()
print("Run ns dig for deseretnews.com")
subprocess.call(["dig","deseretnews.com"])
print()
print("Run Host for deseretnews.com")
subprocess.call(["host","deseretnews.com"])

time.sleep(3)

print("#3")
print()
print("MX servers")
print("__________")
print()
print("Run nslookup for MX servers for weber.edu")
subprocess.call(["nslookup","-query-mx", "weber.edu"])
print()
print("Run ns dig for MX servers for weber.edu")
subprocess.call(["dig", "weber.edu", "MX", "+short"])
print()
print("Run Host for MX servers for weber.edu")
subprocess.call(["host", "-t", "MX", "weber.edu"])

print("Run nslookup for MX servers for gmail.com")
subprocess.call(["nslookup","-query-mx", "gmail.com"])
print()
print("Run ns dig for MX servers for gmail.com")
subprocess.call(["dig", "gmail.com", "MX", "+short"])
print()
print("Run Host for MX servers for gmail.com")
subprocess.call(["host", "-t", "MX", "gmail.com"])

time.sleep(3)

print("#4")
print()
print("NS servers")
print("__________")
print()
print("Run nslookup for NS servers for yahoo.com")
subprocess.call(["nslookup","-query-ns", "yahoo.com"])
print()
print("Run ns dig for NS servers for yahoo.com")
subprocess.call(["dig", "yahoo.com", "NS", "+short"])
print()
print("Run Host for NS servers for yahoo.com")
subprocess.call(["host", "-t", "NS", "yahoo.com"])

print("Run nslookup for NS servers for microsoft.com")
subprocess.call(["nslookup","-query-ns", "microsoft.com"])
print()
print("Run ns dig for NS servers for microsoft.com")
subprocess.call(["dig", "microsoft.com", "NS", "+short"])
print()
print("Run Host for NS servers for microsoft.com")
subprocess.call(["host", "-t", "NS", "microsoft.com"])

time.sleep(3)

print("#5")
print()
print("Change DNS server")
print("__________")
print()
print("Run nslookup using another DNS server for novell.com")
subprocess.call(["nslookup","-query-mx", "novell.com", "8.8.8.8" ])
print()
print("Run ns dig using another DNS server for novell.com")
subprocess.call(["dig", "@8.8.8.8", "novell.com"])
print()
print("Run Host using another DNS server for novell.com")
subprocess.call(["host", "novell.com", "8.8.8.8"])

print("Run nslookup using another DNS server for hp.com")
subprocess.call(["nslookup","-query-mx", "hp.com", "8.8.8.8" ])
print()
print("Run ns dig using another DNS server for hp.com")
subprocess.call(["dig", "@8.8.8.8", "hp.com"])
print()
print("Run Host using another DNS server for hp.com")
subprocess.call(["host", "hp.com", "8.8.8.8"])

time.sleep(3)
